import React, { FormEvent, useEffect, useMemo, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { api } from './api/client'
import { initializeTelegram } from './telegram'
import type { AuthMe, Customer, CustomerProfile, Dashboard, Item, ItemStatus, PaymentEvidence } from './types'
import './style.css'
import './enhancements.css'

type View = 'home'|'items'|'warehouse'|'customers'|'profile'
const allStatuses:ItemStatus[]=['TO_BUY','ORDERED','PURCHASED_OFFLINE','ON_THE_WAY_TO_US','READY_FOR_PICKUP','RECEIVED','ASSIGNED_TO_SHIPMENT','SHIPPED','DELIVERED','CANCELLED','RETURN_IN_PROGRESS','RETURNED']
const labels:Record<ItemStatus,string>={TO_BUY:'Нужно купить',ORDERED:'Заказано',PURCHASED_OFFLINE:'Куплено офлайн',ON_THE_WAY_TO_US:'Едет к нам',READY_FOR_PICKUP:'Ждёт получения',RECEIVED:'Получено',ASSIGNED_TO_SHIPMENT:'Готовится к отправке',SHIPPED:'Отправлено',DELIVERED:'Доставлено',CANCELLED:'Отменено',RETURN_IN_PROGRESS:'Возврат',RETURNED:'Возвращено'}
const transitions:Record<ItemStatus,ItemStatus[]>={TO_BUY:['ORDERED','PURCHASED_OFFLINE','CANCELLED'],ORDERED:['ON_THE_WAY_TO_US','READY_FOR_PICKUP','CANCELLED'],PURCHASED_OFFLINE:['RECEIVED','RETURN_IN_PROGRESS'],ON_THE_WAY_TO_US:['READY_FOR_PICKUP','RECEIVED','RETURN_IN_PROGRESS'],READY_FOR_PICKUP:['RECEIVED','RETURN_IN_PROGRESS'],RECEIVED:['ASSIGNED_TO_SHIPMENT','RETURN_IN_PROGRESS'],ASSIGNED_TO_SHIPMENT:['RECEIVED','SHIPPED'],SHIPPED:['DELIVERED'],RETURN_IN_PROGRESS:['RETURNED','RECEIVED'],DELIVERED:[],CANCELLED:[],RETURNED:[]}

function App(){
  const initData=useMemo(initializeTelegram,[])
  const [me,setMe]=useState<AuthMe|null>(null),[dashboard,setDashboard]=useState<Dashboard|null>(null)
  const [items,setItems]=useState<Item[]>([]),[customers,setCustomers]=useState<Customer[]>([])
  const [evidence,setEvidence]=useState<PaymentEvidence[]>([])
  const initialView=new URLSearchParams(window.location.search).get('view')==='profile'?'profile':'home'
  const [profile,setProfile]=useState<CustomerProfile|null>(null),[view,setView]=useState<View>(initialView)
  const [loading,setLoading]=useState(true),[updating,setUpdating]=useState<string|null>(null),[error,setError]=useState<string|null>(null)
  useEffect(()=>{if(!initData){setError('Откройте приложение из личного чата с Telegram-ботом.');setLoading(false);return}Promise.all([api.me(initData),api.dashboard(initData),api.items(initData),api.profile(initData)]).then(async([identity,stats,loadedItems,loadedProfile])=>{setMe(identity);setDashboard(stats);setItems(loadedItems);setProfile(loadedProfile);if(identity.role!=='CUSTOMER'){const [loadedCustomers,loadedEvidence]=await Promise.all([api.customers(initData),api.paymentEvidence(initData)]);setCustomers(loadedCustomers);setEvidence(loadedEvidence)}}).catch((reason:Error)=>setError(reason.message)).finally(()=>setLoading(false))},[initData])
  if(loading)return <State title="Загружаем заказы…"/>
  if(!me||!dashboard)return <State title="Не удалось открыть приложение" text={error??'Нет данных пользователя'}/>
  const admin=me.role==='ADMIN'
  const staff=me.role!=='CUSTOMER'
  const refreshDashboard=()=>api.dashboard(initData).then(setDashboard)
  const updateStatus=async(item:Item,target:ItemStatus)=>{setUpdating(item.id);setError(null);try{const updated=await api.updateItemStatus(initData,item.id,target);setItems(current=>current.map(value=>value.id===updated.id?updated:value));await refreshDashboard()}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось изменить статус')}finally{setUpdating(null)}}
  const correctStatus=async(item:Item,target:ItemStatus)=>{const reason=window.prompt('Укажите причину исправления статуса (обязательно):')?.trim();if(!reason)return;setUpdating(item.id);setError(null);try{const updated=await api.correctItemStatus(initData,item.id,target,reason);setItems(current=>current.map(value=>value.id===updated.id?updated:value));await refreshDashboard()}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось исправить статус')}finally{setUpdating(null)}}
  const names=new Map(customers.map(customer=>[customer.id,customer.display_name]))
  const navigation:{id:View;label:string}[]=staff?[{id:'home',label:'Главная'},{id:'items',label:'Заказы'},{id:'warehouse',label:'Склад'},{id:'customers',label:'Клиенты'}]:[{id:'home',label:'Главная'},{id:'items',label:'Мои товары'},{id:'profile',label:'Профиль'}]
  const visibleItems=view==='warehouse'?items.filter(item=>['RECEIVED','ASSIGNED_TO_SHIPMENT'].includes(item.status)):items
  return <div className="app-shell"><header><p className="eyebrow">TELEGRAM ORDERS</p><h1>{admin?'Управление заказами':staff?'Просмотр заказов':'Мои заказы'}</h1></header><main>{error&&<div className="error-banner">{error}<button onClick={()=>setError(null)}>×</button></div>}
    {view==='home'&&<DashboardView data={dashboard} staff={staff}/>} {(view==='items'||view==='warehouse')&&<ItemsView items={visibleItems} staff={staff} canManage={admin} updating={updating} customerNames={names} evidence={evidence} initData={initData} onEvidence={value=>setEvidence(current=>[value,...current])} onTransition={updateStatus} onCorrect={correctStatus}/>} {view==='customers'&&<CustomersView customers={customers}/>} {view==='profile'&&profile&&<ProfileView initData={initData} profile={profile} onSaved={setProfile}/>}</main><nav>{navigation.map(item=><button key={item.id} className={view===item.id?'active':''} onClick={()=>setView(item.id)}>{item.label}</button>)}</nav></div>
}

function DashboardView({data,staff}:{data:Dashboard;staff:boolean}){const metrics=[['Нужно купить',data.to_buy],['Едет к нам',data.on_the_way],['Получено',data.received],[staff?'В посылках':'Готовится',data.assigned_to_shipment]];return <><section className="metrics">{metrics.map(([label,value])=><article className="metric" key={label}><strong>{value}</strong><span>{label}</span></article>)}</section><section className="card"><h2>{staff?'Сводка заказов':'Статус отправки'}</h2><p>{data.received?`${data.received} товар(а) уже получено.`:'Полученных товаров пока нет.'}</p></section></>}

function ItemsView({items,staff,canManage,updating,customerNames,evidence,initData,onEvidence,onTransition,onCorrect}:{items:Item[];staff:boolean;canManage:boolean;updating:string|null;customerNames:Map<string,string>;evidence:PaymentEvidence[];initData:string;onEvidence:(value:PaymentEvidence)=>void;onTransition:(item:Item,target:ItemStatus)=>void;onCorrect:(item:Item,target:ItemStatus)=>void}){if(!items.length)return <State title="Здесь пока пусто" text="Новые товары появятся после отправки ссылки боту."/>;return <section className="list">{items.map(item=><article className="item item-manage" key={item.id}><div className="item-details"><h2>{customerNames.get(item.customer_id)??new URL(item.product_url).hostname.replace('www.','')}</h2><a href={item.product_url} target="_blank" rel="noreferrer">Открыть товар ↗</a><p>{[item.size&&`Размер ${item.size}`,item.color&&`Цвет ${item.color}`,`Количество ${item.quantity}`].filter(Boolean).join(' · ')}</p>{item.customer_note&&<p>Комментарий: {item.customer_note}</p>}<small>Заказ {item.id}</small>{staff&&<PaymentPanel initData={initData} item={item} evidence={evidence.filter(value=>value.item_id===item.id)} canManage={canManage} onAdded={onEvidence}/>}</div><div className="item-actions"><span className={`status status-${item.status.toLowerCase()}`}>{labels[item.status]}</span>{canManage&&transitions[item.status].length>0&&<select aria-label="Изменить статус" disabled={updating===item.id} value="" onChange={event=>onTransition(item,event.target.value as ItemStatus)}><option value="" disabled>{updating===item.id?'Сохраняем…':'Следующий статус'}</option>{transitions[item.status].map(target=><option value={target} key={target}>{labels[target]}</option>)}</select>}{canManage&&<select className="correction" aria-label="Исправить статус" disabled={updating===item.id} value="" onChange={event=>onCorrect(item,event.target.value as ItemStatus)}><option value="" disabled>Исправить ошибочный статус</option>{allStatuses.filter(target=>target!==item.status).map(target=><option value={target} key={target}>{labels[target]}</option>)}</select>}</div></article>)}</section>}

function PaymentPanel({initData,item,evidence,canManage,onAdded}:{initData:string;item:Item;evidence:PaymentEvidence[];canManage:boolean;onAdded:(value:PaymentEvidence)=>void}){const [note,setNote]=useState(''),[file,setFile]=useState<File|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState<string|null>(null);const submit=async(event:FormEvent)=>{event.preventDefault();if(!note.trim()&&!file){setMessage('Добавьте текст или изображение.');return}setSaving(true);setMessage(null);try{const saved=await api.addPaymentEvidence(initData,item.id,note,file);onAdded(saved);setNote('');setFile(null);setMessage('Информация об оплате сохранена.')}catch(reason){setMessage(reason instanceof Error?reason.message:'Не удалось сохранить')}finally{setSaving(false)}};const openImage=async(id:string)=>{try{const url=await api.paymentEvidenceImage(initData,id);window.open(url,'_blank','noopener,noreferrer');window.setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(reason){setMessage(reason instanceof Error?reason.message:'Не удалось открыть изображение')}};return <details className="payment-panel"><summary>Оплата {evidence.length?`(${evidence.length})`:''}</summary>{evidence.map(value=><div className="payment-entry" key={value.id}>{value.note&&<p>{value.note}</p>}{value.has_image&&<button type="button" onClick={()=>openImage(value.id)}>Открыть чек ↗</button>}</div>)}{canManage&&<form onSubmit={submit}><textarea placeholder="Комментарий об оплате" value={note} onChange={event=>setNote(event.target.value)}/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setFile(event.target.files?.[0]??null)}/><button className="primary" disabled={saving}>{saving?'Сохраняем…':'Добавить информацию'}</button>{message&&<p>{message}</p>}</form>}</details>}

function CustomersView({customers}:{customers:Customer[]}){if(!customers.length)return <State title="Клиентов пока нет"/>;return <section className="list">{customers.map(customer=><article className="item" key={customer.id}><div><h2>{customer.display_name}</h2><p>{customer.phone??'Телефон не указан'}</p></div><span className="status">{customer.collection_status}</span></article>)}</section>}

function ProfileView({initData,profile,onSaved}:{initData:string;profile:CustomerProfile;onSaved:(profile:CustomerProfile)=>void}){const [form,setForm]=useState(profile),[saving,setSaving]=useState(false),[message,setMessage]=useState<string|null>(null);const field=(name:keyof CustomerProfile,value:string)=>setForm(current=>({...current,[name]:value}));const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setMessage(null);try{const {complete:_,...payload}=form;const saved=await api.saveProfile(initData,payload);setForm(saved);onSaved(saved);setMessage('Профиль и адрес сохранены. Теперь можно оформлять заказы.')}catch(reason){setMessage(reason instanceof Error?reason.message:'Не удалось сохранить профиль')}finally{setSaving(false)}};return <form className="card profile-form" onSubmit={submit}><h2>Получатель и доставка</h2><p>Заполните данные так, как они должны быть указаны на отправлении.</p><label>Фамилия, имя и отчество<input required minLength={5} value={form.display_name} onChange={event=>field('display_name',event.target.value)}/></label><label>Телефон<input required type="tel" value={form.phone??''} onChange={event=>field('phone',event.target.value)}/></label><div className="form-row"><label>Страна (код)<input required maxLength={2} placeholder="EE" value={form.country_code??''} onChange={event=>field('country_code',event.target.value)}/></label><label>Индекс<input required value={form.postal_code??''} onChange={event=>field('postal_code',event.target.value)}/></label></div><label>Регион<input value={form.region??''} onChange={event=>field('region',event.target.value)}/></label><label>Город<input required value={form.city??''} onChange={event=>field('city',event.target.value)}/></label><label>Улица, дом, квартира<input required value={form.address_line1??''} onChange={event=>field('address_line1',event.target.value)}/></label><label>Дополнение к адресу<input value={form.address_line2??''} onChange={event=>field('address_line2',event.target.value)}/></label><button className="primary" disabled={saving}>{saving?'Сохраняем…':'Сохранить профиль'}</button>{message&&<p className="form-message">{message}</p>}</form>}

function State({title,text}:{title:string;text?:string}){return <main className="state"><div><p className="eyebrow">TELEGRAM ORDERS</p><h1>{title}</h1>{text&&<p>{text}</p>}</div></main>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
