import React, { FormEvent, useEffect, useMemo, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { api } from './api/client'
import { initializeTelegram } from './telegram'
import type { AuthMe, Customer, CustomerProfile, Dashboard, Item, ItemStatus, PaymentEvidence, Shipment } from './types'
import './style.css'
import './enhancements.css'

type View = 'home'|'items'|'warehouse'|'customers'|'profile'
const allStatuses:ItemStatus[]=['TO_BUY','ORDERED','PURCHASED_OFFLINE','ON_THE_WAY_TO_US','READY_FOR_PICKUP','RECEIVED','ASSIGNED_TO_SHIPMENT','SHIPPED','DELIVERED','CANCELLED','RETURN_IN_PROGRESS','RETURNED']
const labels:Record<ItemStatus,string>={TO_BUY:'Нужно купить',ORDERED:'Заказано',PURCHASED_OFFLINE:'Куплено офлайн',ON_THE_WAY_TO_US:'Едет к нам',READY_FOR_PICKUP:'Ждёт получения',RECEIVED:'Получено',ASSIGNED_TO_SHIPMENT:'Готовится к отправке',SHIPPED:'Отправлено',DELIVERED:'Доставлено',CANCELLED:'Отменено',RETURN_IN_PROGRESS:'Возврат',RETURNED:'Возвращено'}
const transitions:Record<ItemStatus,ItemStatus[]>={TO_BUY:['ORDERED','PURCHASED_OFFLINE','CANCELLED'],ORDERED:['ON_THE_WAY_TO_US','READY_FOR_PICKUP','CANCELLED'],PURCHASED_OFFLINE:['RECEIVED','RETURN_IN_PROGRESS'],ON_THE_WAY_TO_US:['READY_FOR_PICKUP','RECEIVED','RETURN_IN_PROGRESS'],READY_FOR_PICKUP:['RECEIVED','RETURN_IN_PROGRESS'],RECEIVED:['RETURN_IN_PROGRESS'],ASSIGNED_TO_SHIPMENT:['RECEIVED'],SHIPPED:['DELIVERED'],RETURN_IN_PROGRESS:['RETURNED','RECEIVED'],DELIVERED:[],CANCELLED:[],RETURNED:[]}

function App(){
  const initData=useMemo(initializeTelegram,[])
  const [me,setMe]=useState<AuthMe|null>(null),[dashboard,setDashboard]=useState<Dashboard|null>(null)
  const [items,setItems]=useState<Item[]>([]),[customers,setCustomers]=useState<Customer[]>([])
  const [evidence,setEvidence]=useState<PaymentEvidence[]>([]),[shipments,setShipments]=useState<Shipment[]>([])
  const initialView=new URLSearchParams(window.location.search).get('view')==='profile'?'profile':'home'
  const [profile,setProfile]=useState<CustomerProfile|null>(null),[view,setView]=useState<View>(initialView)
  const [loading,setLoading]=useState(true),[updating,setUpdating]=useState<string|null>(null),[error,setError]=useState<string|null>(null)
  useEffect(()=>{if(!initData){setError('Откройте приложение из личного чата с Telegram-ботом.');setLoading(false);return}Promise.all([api.me(initData),api.dashboard(initData),api.items(initData),api.profile(initData),api.shipments(initData)]).then(async([identity,stats,loadedItems,loadedProfile,loadedShipments])=>{setMe(identity);setDashboard(stats);setItems(loadedItems);setProfile(loadedProfile);setShipments(loadedShipments);if(identity.role!=='CUSTOMER'){const [loadedCustomers,loadedEvidence]=await Promise.all([api.customers(initData),api.paymentEvidence(initData)]);setCustomers(loadedCustomers);setEvidence(loadedEvidence)}}).catch((reason:Error)=>setError(reason.message)).finally(()=>setLoading(false))},[initData])
  if(loading)return <State title="Загружаем заказы…"/>
  if(!me||!dashboard)return <State title="Не удалось открыть приложение" text={error??'Нет данных пользователя'}/>
  const admin=me.role==='ADMIN'
  const staff=me.role!=='CUSTOMER'
  const refreshDashboard=()=>api.dashboard(initData).then(setDashboard)
  const updateStatus=async(item:Item,target:ItemStatus)=>{setUpdating(item.id);setError(null);try{const updated=await api.updateItemStatus(initData,item.id,target);setItems(current=>current.map(value=>value.id===updated.id?updated:value));await refreshDashboard()}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось изменить статус')}finally{setUpdating(null)}}
  const correctStatus=async(item:Item,target:ItemStatus,reason:string)=>{setUpdating(item.id);setError(null);try{const updated=await api.correctItemStatus(initData,item.id,target,reason);setItems(current=>current.map(value=>value.id===updated.id?updated:value));await refreshDashboard()}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось исправить статус');throw cause}finally{setUpdating(null)}}
  const names=new Map(customers.map(customer=>[customer.id,customer.display_name]))
  const navigation:{id:View;label:string}[]=staff?[{id:'home',label:'Главная'},{id:'items',label:'Заказы'},{id:'warehouse',label:'Склад'},{id:'customers',label:'Клиенты'}]:[{id:'home',label:'Главная'},{id:'items',label:'Мои товары'},{id:'profile',label:'Профиль'}]
  const visibleItems=view==='warehouse'?items.filter(item=>['PURCHASED_OFFLINE','RECEIVED','ASSIGNED_TO_SHIPMENT'].includes(item.status)):items
  return <div className="app-shell"><header><p className="eyebrow">TELEGRAM ORDERS</p><h1>{admin?'Управление заказами':staff?'Просмотр заказов':'Мои заказы'}</h1></header><main>{error&&<div className="error-banner">{error}<button onClick={()=>setError(null)}>×</button></div>}
    {view==='home'&&<DashboardView data={dashboard} staff={staff} shipments={shipments} items={items}/>} {(view==='items'||view==='warehouse')&&<ItemsView items={visibleItems} staff={staff} canManage={admin} updating={updating} customerNames={names} evidence={evidence} initData={initData} onEvidence={value=>setEvidence(current=>[value,...current])} onTracking={value=>setShipments(current=>[value,...current.filter(shipment=>shipment.id!==value.id)])} onTransition={updateStatus} onCorrect={correctStatus}/>} {view==='customers'&&<CustomersView customers={customers} items={items} shipments={shipments} canManage={admin} initData={initData} onCreated={async shipment=>{setShipments(current=>[shipment,...current]);setItems(await api.items(initData));await refreshDashboard()}}/>} {view==='profile'&&profile&&<ProfileView initData={initData} profile={profile} onSaved={setProfile}/>}</main><nav>{navigation.map(item=><button key={item.id} className={view===item.id?'active':''} onClick={()=>setView(item.id)}>{item.label}</button>)}</nav></div>
}

function DashboardView({data,staff,shipments,items}:{data:Dashboard;staff:boolean;shipments:Shipment[];items:Item[]}){const metrics=staff?[['Нужно купить',data.to_buy],['Едет к нам',data.on_the_way],['Получено',data.received],['В посылках',data.assigned_to_shipment]]:[['Заказано',data.ordered],['Выкуплено',data.purchased],['На складе в Испании',data.in_spain],['Отправлено',data.shipped]];return <><section className="metrics">{metrics.map(([label,value])=><article className="metric" key={label}><strong>{value}</strong><span>{label}</span></article>)}</section>{staff?<section className="card"><h2>Сводка заказов</h2><p>{data.received?`${data.received} товар(а) уже получено.`:'Полученных товаров пока нет.'}</p></section>:<ShipmentsPanel shipments={shipments} items={items}/>}</>}

function ShipmentsPanel({shipments,items}:{shipments:Shipment[];items:Item[]}){return <section className="card"><h2>Отправления и трек-номера</h2>{shipments.length?shipments.map(shipment=><ShipmentEntry key={shipment.id} shipment={shipment} items={items}/>):<p>Активных отправлений пока нет.</p>}</section>}

function ShipmentEntry({shipment,items}:{shipment:Shipment;items:Item[]}){const contents=shipment.item_ids.map(id=>items.find(item=>item.id===id)).filter((item):item is Item=>Boolean(item));return <div className="shipment-entry"><strong>{shipment.carrier??'Служба доставки'}</strong><p>Трек-номер: {shipment.tracking_number??'ещё не указан'}</p><p>{contents.length?contents.map(item=>`${new URL(item.product_url).hostname.replace('www.','')}${item.size?`, размер ${item.size}`:''}`).join(' · '):`${shipment.item_ids.length} поз.`}</p><small>{shipment.status==='SHIPPED'?'Отправлено':shipment.status} · {new Date(shipment.created_at).toLocaleDateString()}</small></div>}

function ItemsView({items,staff,canManage,updating,customerNames,evidence,initData,onEvidence,onTracking,onTransition,onCorrect}:{items:Item[];staff:boolean;canManage:boolean;updating:string|null;customerNames:Map<string,string>;evidence:PaymentEvidence[];initData:string;onEvidence:(value:PaymentEvidence)=>void;onTracking:(value:Shipment)=>void;onTransition:(item:Item,target:ItemStatus)=>void;onCorrect:(item:Item,target:ItemStatus,reason:string)=>Promise<void>}){if(!items.length)return <State title="Здесь пока пусто" text="Новые товары появятся после отправки ссылки боту."/>;return <section className="list">{items.map(item=><article className="item item-manage" key={item.id}><div className="item-details"><h2>{customerNames.get(item.customer_id)??new URL(item.product_url).hostname.replace('www.','')}</h2><a href={item.product_url} target="_blank" rel="noreferrer">Открыть товар ↗</a><p>{[item.size&&`Размер ${item.size}`,item.color&&`Цвет ${item.color}`,`Количество ${item.quantity}`].filter(Boolean).join(' · ')}</p>{item.customer_note&&<p>Комментарий: {item.customer_note}</p>}<small>Заказ {item.id}</small>{staff&&<PaymentPanel initData={initData} item={item} evidence={evidence.filter(value=>value.item_id===item.id)} canManage={canManage} onAdded={onEvidence}/>} {canManage&&item.status==='SHIPPED'&&<TrackingPanel initData={initData} item={item} onSaved={onTracking}/>}</div><div className="item-actions"><span className={`status status-${item.status.toLowerCase()}`}>{labels[item.status]}</span>{canManage&&transitions[item.status].length>0&&<select aria-label="Изменить статус" disabled={updating===item.id} value="" onChange={event=>onTransition(item,event.target.value as ItemStatus)}><option value="" disabled>{updating===item.id?'Сохраняем…':'Следующий статус'}</option>{transitions[item.status].map(target=><option value={target} key={target}>{labels[target]}</option>)}</select>}{canManage&&<CorrectionPanel item={item} saving={updating===item.id} onCorrect={onCorrect}/>}</div></article>)}</section>}

function TrackingPanel({initData,item,onSaved}:{initData:string;item:Item;onSaved:(value:Shipment)=>void}){const [carrier,setCarrier]=useState(''),[tracking,setTracking]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState<string|null>(null);const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setMessage(null);try{const shipment=await api.saveItemTracking(initData,item.id,carrier,tracking);onSaved(shipment);setMessage('Трек-номер сохранён и доступен клиенту.')}catch(reason){setMessage(reason instanceof Error?reason.message:'Не удалось сохранить трек-номер')}finally{setSaving(false)}};return <details className="tracking-panel"><summary>Добавить или изменить трек-номер</summary><form onSubmit={submit}><input required minLength={2} placeholder="Служба доставки" value={carrier} onChange={event=>setCarrier(event.target.value)}/><input required minLength={3} placeholder="Трек-номер" value={tracking} onChange={event=>setTracking(event.target.value)}/><button className="primary" disabled={saving}>{saving?'Сохраняем…':'Сохранить трек-номер'}</button>{message&&<p>{message}</p>}</form></details>}

function CorrectionPanel({item,saving,onCorrect}:{item:Item;saving:boolean;onCorrect:(item:Item,target:ItemStatus,reason:string)=>Promise<void>}){const [target,setTarget]=useState<ItemStatus|''>(''),[reason,setReason]=useState(''),[message,setMessage]=useState<string|null>(null);const submit=async(event:FormEvent)=>{event.preventDefault();if(!target||reason.trim().length<3){setMessage('Выберите статус и укажите причину не короче 3 символов.');return}setMessage(null);try{await onCorrect(item,target,reason.trim());setTarget('');setReason('');setMessage('Статус исправлен.')}catch{setMessage('Не удалось исправить статус. Проверьте сообщение сверху.')}};return <details className="correction-panel"><summary>Исправить ошибочный статус</summary><form onSubmit={submit}><select required disabled={saving} value={target} onChange={event=>setTarget(event.target.value as ItemStatus)}><option value="" disabled>Выберите правильный статус</option>{allStatuses.filter(value=>value!==item.status).map(value=><option value={value} key={value}>{labels[value]}</option>)}</select><input required minLength={3} placeholder="Причина исправления" value={reason} onChange={event=>setReason(event.target.value)}/><button className="primary" disabled={saving}>{saving?'Сохраняем…':'Исправить статус'}</button>{message&&<p>{message}</p>}</form></details>}

function PaymentPanel({initData,item,evidence,canManage,onAdded}:{initData:string;item:Item;evidence:PaymentEvidence[];canManage:boolean;onAdded:(value:PaymentEvidence)=>void}){const [note,setNote]=useState(''),[file,setFile]=useState<File|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState<string|null>(null);const submit=async(event:FormEvent)=>{event.preventDefault();if(!note.trim()&&!file){setMessage('Добавьте текст или изображение.');return}setSaving(true);setMessage(null);try{const saved=await api.addPaymentEvidence(initData,item.id,note,file);onAdded(saved);setNote('');setFile(null);setMessage('Информация об оплате сохранена.')}catch(reason){setMessage(reason instanceof Error?reason.message:'Не удалось сохранить')}finally{setSaving(false)}};const openImage=async(id:string)=>{try{const url=await api.paymentEvidenceImage(initData,id);window.open(url,'_blank','noopener,noreferrer');window.setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(reason){setMessage(reason instanceof Error?reason.message:'Не удалось открыть изображение')}};return <details className="payment-panel"><summary>Оплата {evidence.length?`(${evidence.length})`:''}</summary>{evidence.map(value=><div className="payment-entry" key={value.id}>{value.note&&<p>{value.note}</p>}{value.has_image&&<button type="button" onClick={()=>openImage(value.id)}>Открыть чек ↗</button>}</div>)}{canManage&&<form onSubmit={submit}><textarea placeholder="Комментарий об оплате" value={note} onChange={event=>setNote(event.target.value)}/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>setFile(event.target.files?.[0]??null)}/><button className="primary" disabled={saving}>{saving?'Сохраняем…':'Добавить информацию'}</button>{message&&<p>{message}</p>}</form>}</details>}

function customerData(customer:Customer){return [customer.recipient_name||customer.display_name,customer.phone&&`Телефон: ${customer.phone}`,[customer.postal_code,customer.city].filter(Boolean).join(' '),customer.region,customer.address_line1,customer.address_line2,customer.country_code&&`Страна: ${customer.country_code}`].filter(Boolean).join('\n')}

async function copyText(value:string){try{await navigator.clipboard.writeText(value)}catch{const area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove()}}

function CustomersView({customers,items,shipments,canManage,initData,onCreated}:{customers:Customer[];items:Item[];shipments:Shipment[];canManage:boolean;initData:string;onCreated:(shipment:Shipment)=>Promise<void>}){if(!customers.length)return <State title="Клиентов пока нет"/>;return <section className="list">{customers.map(customer=>{const customerItems=items.filter(value=>value.customer_id===customer.id);const customerShipments=shipments.filter(value=>value.customer_id===customer.id);return <article className="item customer-card" key={customer.id}><div className="item-details"><h2>{customer.display_name}</h2><p>{customer.phone??'Телефон не указан'}</p><CustomerSummary items={customerItems} shipments={customerShipments}/><CustomerDetails customer={customer}/>{customerShipments.map(value=><ShipmentEntry key={value.id} shipment={value} items={items}/>)}{canManage&&<ShipmentForm customer={customer} items={customerItems.filter(value=>['PURCHASED_OFFLINE','RECEIVED'].includes(value.status))} initData={initData} onCreated={onCreated}/>}</div></article>})}</section>}

function CustomerSummary({items,shipments}:{items:Item[];shipments:Shipment[]}){const fresh=items.filter(item=>item.status==='TO_BUY').length;const purchased=items.filter(item=>['ORDERED','ON_THE_WAY_TO_US','READY_FOR_PICKUP'].includes(item.status)).length;const warehouse=items.filter(item=>['PURCHASED_OFFLINE','RECEIVED','ASSIGNED_TO_SHIPMENT'].includes(item.status)).length;const inTransit=shipments.filter(shipment=>shipment.item_ids.some(id=>items.find(item=>item.id===id)?.status==='SHIPPED')).length;const parts=[fresh&&`${fresh} новых`,purchased&&`${purchased} выкуплено`,warehouse&&`${warehouse} на складе`,inTransit&&`${inTransit} ${inTransit===1?'посылка':'посылки'} в пути`].filter(Boolean);return <p className="customer-summary">{parts.length?parts.join(' · '):'Нет активных заказов'}</p>}

function CustomerDetails({customer}:{customer:Customer}){const [copied,setCopied]=useState(false);const data=customerData(customer);const copy=async()=>{await copyText(data);setCopied(true);window.setTimeout(()=>setCopied(false),2000)};return <details className="customer-details"><summary>Показать данные для отправки</summary><div className="customer-address"><p>{data||'Адрес ещё не заполнен.'}</p><button type="button" className="primary" disabled={!data} onClick={copy}>{copied?'Скопировано ✓':'Копировать данные'}</button></div></details>}

function ShipmentForm({customer,items,initData,onCreated}:{customer:Customer;items:Item[];initData:string;onCreated:(shipment:Shipment)=>Promise<void>}){const [selected,setSelected]=useState<string[]>([]),[carrier,setCarrier]=useState(''),[tracking,setTracking]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState<string|null>(null);if(!items.length)return null;const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);const allSelected=selected.length===items.length;const submit=async(event:FormEvent)=>{event.preventDefault();if(!selected.length){setMessage('Выберите хотя бы один товар со склада.');return}setSaving(true);setMessage(null);try{const shipment=await api.createShipment(initData,customer.id,selected,carrier,tracking);await onCreated(shipment);setSelected([]);setCarrier('');setTracking('');setMessage('Посылка создана, выбранные товары отмечены отправленными.')}catch(reason){setMessage(reason instanceof Error?reason.message:'Не удалось создать отправление')}finally{setSaving(false)}};return <details className="shipment-form"><summary>Создать новую посылку ({items.length} доступно)</summary><form onSubmit={submit}><div className="shipment-selection-head"><strong>Выбрано: {selected.length}</strong><button type="button" onClick={()=>setSelected(allSelected?[]:items.map(item=>item.id))}>{allSelected?'Снять выбор':'Выбрать все'}</button></div>{items.map(item=><label className={`shipment-item ${selected.includes(item.id)?'selected':''}`} key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/><span><strong>{new URL(item.product_url).hostname.replace('www.','')}</strong><small>{item.size?`Размер ${item.size}`:'Без размера'} · заказ {item.id.slice(0,8)}</small></span></label>)}<input required minLength={2} placeholder="Служба доставки" value={carrier} onChange={event=>setCarrier(event.target.value)}/><input required minLength={3} placeholder="Трек-номер посылки" value={tracking} onChange={event=>setTracking(event.target.value)}/><button className="primary" disabled={saving}>{saving?'Сохраняем…':'Создать посылку и сохранить трек'}</button>{message&&<p>{message}</p>}</form></details>}

function ProfileView({initData,profile,onSaved}:{initData:string;profile:CustomerProfile;onSaved:(profile:CustomerProfile)=>void}){const [form,setForm]=useState(profile),[saving,setSaving]=useState(false),[message,setMessage]=useState<string|null>(null);const field=(name:keyof CustomerProfile,value:string)=>setForm(current=>({...current,[name]:value}));const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setMessage(null);try{const {complete:_,...payload}=form;const saved=await api.saveProfile(initData,payload);setForm(saved);onSaved(saved);setMessage('Профиль и адрес сохранены. Теперь можно оформлять заказы.')}catch(reason){setMessage(reason instanceof Error?reason.message:'Не удалось сохранить профиль')}finally{setSaving(false)}};return <form className="card profile-form" onSubmit={submit}><h2>Получатель и доставка</h2><p>Заполните данные так, как они должны быть указаны на отправлении.</p><label>Фамилия, имя и отчество<input required minLength={5} value={form.display_name} onChange={event=>field('display_name',event.target.value)}/></label><label>Телефон<input required minLength={5} type="tel" placeholder="+372 5555 0000" value={form.phone??''} onChange={event=>field('phone',event.target.value)}/></label><div className="form-row"><label>Страна (код)<input required minLength={2} maxLength={2} pattern="[A-Za-z]{2}" placeholder="EE" value={form.country_code??''} onChange={event=>field('country_code',event.target.value)}/></label><label>Индекс<input required minLength={2} value={form.postal_code??''} onChange={event=>field('postal_code',event.target.value)}/></label></div><label>Регион<input value={form.region??''} onChange={event=>field('region',event.target.value)}/></label><label>Город<input required minLength={2} value={form.city??''} onChange={event=>field('city',event.target.value)}/></label><label>Улица, дом, квартира<input required minLength={5} placeholder="Улица, дом, квартира" value={form.address_line1??''} onChange={event=>field('address_line1',event.target.value)}/></label><label>Дополнение к адресу<input value={form.address_line2??''} onChange={event=>field('address_line2',event.target.value)}/></label><button className="primary" disabled={saving}>{saving?'Сохраняем…':'Сохранить профиль'}</button>{message&&<p className="form-message">{message}</p>}</form>}

function State({title,text}:{title:string;text?:string}){return <main className="state"><div><p className="eyebrow">TELEGRAM ORDERS</p><h1>{title}</h1>{text&&<p>{text}</p>}</div></main>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
